### ISSUE TITLE
로컬 스토리지 auth

### ISSUE THREAD

**Issue by jihoon135** [ray9583/SeeLook#10]
1. 로컬 스토리지 데이터가 안들어와지네요.
2. token console을 찍어보니 null값이라고 나오네요.

좀 더 알아보겠지만, 혹시나 도움 받을 수 있으면 ㅎㅎ..

**Comment by Jinviz** [comment]
해당 로직을 구현한 컴포넌트가 어디인가요

**Comment by jihoon135** [comment]
utils/auth.js에서 isAuthenticated 함수입니다. 

ProtectedRoute 컴포넌트에서 !isAuthenticated(사용자 인증이 되지 않았을 경우) navigate를 통해 로그인 페이지로 이동하는 로직이에요.

**Comment by Jinviz** [comment]
해당 부분은 주말에 확인해보겠습니다. 
혼자서 해결되지 않는다면 스타일링과 반응형 진행해주세요.
