### ISSUE TITLE
이미지 카테고리 선택 버튼 구현

### ISSUE THREAD

**Issue by minggichae** [ray9583/SeeLook#21]
## Description
- lookbook 페이지에서 선택한 카테고리의 이미지를 노출 시켜야함. 카테고리를 구분하는 버튼을 만들 것임.

## To-do
- [x] 카테고리 선택 버튼 구현 
- [x] 버튼 스타일링

## Expected time
- ~06-05

## ETC
반응형 작업을 진행 한 후 수정이 필요할 수 있음

**Comment by Jinviz** [comment]
수고하셨습니다. 완료한 이슈라면 클로즈 해주세요.
