### ISSUE TITLE
login, signup css 작업

### ISSUE THREAD

**Issue by jihoon135** [ray9583/SeeLook#23]
## Description
- Login.css(Login, Signup 컴포넌트에 적용 중) 수정

## Ref
- https://inpa.tistory.com/entry/CSS-%F0%9F%92%8D-%EB%A1%9C%EA%B7%B8%EC%9D%B8-%ED%9A%8C%EC%9B%90%EA%B0%80%EC%9E%85-%ED%8E%98%EC%9D%B4%EC%A7%80-%EC%8A%A4%ED%83%80%EC%9D%BC-%F0%9F%96%8C%EF%B8%8F-%EB%AA%A8%EC%9D%8C

## To-do
- [ ] Ref code를 Login.css에 적용 시키기

## Expected time
- ~06-09

## ETC
- 코드 분석 실패로 적용 시키지 못할 수도 있음.

**Comment by Jinviz** [comment]
반응형 작업으로 전환 요청합니다.
