### ISSUE TITLE
이미지 재업로드시 미동작 및 에러 

### ISSUE THREAD

**Issue by Jinviz** [ray9583/SeeLook#28]
## 상황
1. 'Imageupload' 컴포넌트에서 이미지를 업로드 누르고 파일을 연다.
2. 'ImageCropModal' 컴포넌트 창이 열린다.
3. 요소의 바깥 영역이나 'X' 영역을 클릭하면 'UseOnClickOutside' hook이 동작되며 모달창이 닫힌다. 
4. 다시 1번을 반복할시 모달창이 열리지 않는다.

## 코멘트
- 단순한 에러라고 생각은 들지만 동작 순서를 고려하고 코드를 파헤쳐야 하는 소요가 발생됨. 
- 우선순위 작업후 해결할 예정

## ETC
- 팀원들은 이에 확인하면 코멘트 남겨주세요. 추후 에러 발생시 이와 같이 이슈 생성해주세요.

**Comment by minggichae** [comment]
확인했습니다. 에러 발생시 참고 하겠습니다.

**Comment by jihoon135** [comment]
TypeError: Failed to execute 'readAsDataURL' on 'FileReader': parameter 1 is not of type 'Blob'.

**Comment by Jinviz** [comment]
추가적으로 이전 열었던 파일이 아닌 다른 파일을 열기할 땐 정상적으로 동작하는 게 확인되었음.

**Comment by Jinviz** [comment]
## 문제 이유
- file을 upload하면 onChange event가 발생하는데, 같은 파일을 다시 upload할 경우 event가 trigger되지 않는다. (onChange는 실질적인 내용 변화에만 trigger되기 때문)

## 해결
- 따라서 file이 upload되면 값을 초기화해주어야 한다. 내용물을 담고 있는 e.target.value로 초기화
