### ISSUE TITLE
page 디렉토리 구조 및 router 처리 방법

### ISSUE THREAD

**Issue by jihoon135** [ray9583/SeeLook#3]
1. Router 처리를 할 때, 로컬 스토리지에 인증 정보가 저장이 돼 있을 경우 Router 경로를 바로 main 페이지로 이동 시킬 것인지? 
2. 컴포넌트를 바로 불러올 것인지, 페이지 처리를 통해 컴포넌트를 분할 할 것인지?(저는 페이지로 구분 했습니다.)
3. 회의 언제 할까요?_?
4. 바로 push 되는데, 저희 PR 날리는 거는 이제 취소??

**Comment by Jinviz** [comment]
1. yes
2. 후자로 하는 게 자연스럽고 좋습니다.
3. 다음주 수,목 중 얘기를 해봅시다.
4. 바로 push 된다고 PR을 안 하면 안됩니다. PR을 통해 프로젝트 형상 관리하기 위함입니다. 로컬에서의 작업은 자유롭게 하되, 원격저장소에는 안전한 버전 관리를 하기 위해서 PR을 받은 관리자가 머지를 해야합니다. 바로 push 하고 싶다면 따로 feature/ 브랜치를 만들어서 작업하세요.
