### ISSUE TITLE
업로드 페이지, 나의 룩북 페이지 관련 이슈

### ISSUE THREAD

**Issue by jihoon135** [ray9583/SeeLook#47]
## Description
- 업로드 페이지(ClothesUpload, StyleUpload),  나의 룩북 페이지 CSS 개선 사항 논의
- 민기가 말했던 이미지 크기가 균일하지 않게 업로드 되는 현상은 나는 안 나오는데, 확인 바람.
- 오늘의 의상 추천이 온도를 기입 하고 열린 팝업창을 나가면, 조건에 맞는 옷들이 나오는 건지? 아니면 팝업창에서 보여주는 건지? 사용자가 이용하기엔 너무 애매한 UI인 듯. 만약 후자라면, 온도에 맞는 옷이 없을 경우에는 없다는 표시를 해줘야 한다.

## To-do
- [x] 업로드 페이지, 나의 룩북 페이지 CSS 개선 사항 논의
- [x] CSS 개선
- [x] 나의 룩북 페이지 반응형 처리

## Expected time
- ~06-11

## ETC
- 업로드 페이지의 css 파일이 ClothesUpload.css가 있고, StyleUpload.css가 있는데, 구분 되어 있음에도 불구하고 하나의 Uploadcss 파일이 두 개의 js 파일에 적용 되는 현상이 보임. 예를 들어, StyleUpload css가 ClothesUpload와 StyleUpload 둘 다에 적용 되는 것. 그래서 하나의 js 로직에서 class를 수정 해서 구분을 했습니다. 
- 생각처럼 css가 딱딱 안 되네요... 쩝

**Comment by minggichae** [comment]
1. 다같이 논의를 해볼 필요가 있을듯. 글로만 보니 어떤 상황인지 제대로 인지가 되지 않음.
2. 이미지 크기가 균일하지 않게 업로드 되는 현상이 이미지를 불러오는 팝업창을 의미하는 것인지? 팝업창이 맞다면 이미지가 정상적으로 나오는지? (나는 팝업창 이미지가 영역을 벗어남)
3. 팝업창에 들어가면 온도를 입력하게끔 되어있고, 온도를 입력하면 팝업창에서 이미지를 다시 띄우는 형태를 띄고 있음. 온도에 맞는 옷이 없을 경우 없다는 표시를 추가하도록 하겠음.
